plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = '1.0.0-1.21.1'
group = 'com.scouter.cobblelucky'

base {
    archivesName = 'cobblelucky-fabric'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

loom {
    accessWidenerPath = file("src/main/resources/cobblelucky.accesswidener")
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.impactdev.net/repository/development/' }
    maven { url = 'https://thedarkcolour.github.io/KotlinForForge/' }
    maven { url = 'https://maven.parchmentmc.org' }
    maven { url = 'https://cursemaven.com' }

    maven {
        name = 'Cobblemon'
        url = 'https://maven.impactdev.net/repository/development/'
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21.1:2024.11.13@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:0.17.2"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.116.6+1.21.1"

    // Cobblemon for Fabric 1.21.1（从本地 libs 文件夹加载）
    modImplementation files("libs/Cobblemon-fabric-1.7.3+1.21.1.jar")

    // Kotlin for Fabric
    modImplementation "net.fabricmc:fabric-language-kotlin:1.12.0+kotlin.2.0.10"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    options.encoding = 'UTF-8'
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}